//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EURIS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogProduct
    {
        public int IdCatalog { get; set; }
        public int IdProduct { get; set; }
        public int Id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Catalog Catalog { get; set; }
    }
}
